function out1 = Alpha(W,E,k,b,l,L,I,theta0,theta,omega)
%ALPHA
%    OUT1 = ALPHA(W,E,K,B,L,L,I,THETA0,THETA,OMEGA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Apr-2021 17:48:42

t2 = cos(theta);
t3 = sin(theta);
out1 = (-b.*omega+k.*theta0-k.*theta+E.*L.*t3+L.*W.*t3+E.*l.*t2+W.*l.*t2)./I;
