function out1 = X(l,L,theta)
%X
%    OUT1 = X(L,L,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Apr-2021 17:48:42

out1 = L.*sin(theta)+l.*cos(theta);
